# Generated by Django 3.1.7 on 2026-01-08 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'mp3', 'mp4'])]),
        ),
    ]
